version: '3'

services:
  db:
    platform: linux/x86_64
    container_name: coodig-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coodig
      MYSQL_USER: coodig
      MYSQL_PASSWORD: coodig
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-volume-coodig:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3309:3306

volumes:
  db-volume-coodig:
